from __future__ import annotations

import argparse
import re
import shutil
import subprocess
from pathlib import Path


def read_simple_manifest(path: Path) -> dict[str, str]:
    data: dict[str, str] = {}
    section = ""
    for raw_line in path.read_text().splitlines():
        if not raw_line.strip() or raw_line.lstrip().startswith("- "):
            continue
        if not raw_line.startswith(" ") and raw_line.endswith(":"):
            section = raw_line[:-1].strip()
            continue
        match = re.match(r"^\s{2}([A-Za-z0-9_]+):\s*(.*)$", raw_line)
        if not match:
            continue
        key, value = match.groups()
        data[f"{section}.{key}"] = value.strip().strip('"')
    return data


def report_id_for_manifest(manifest: dict[str, str], fallback: str) -> str:
    pr_url = manifest.get("translation.pr_url", "")
    match = re.search(r"/pull/(\d+)", pr_url)
    if match:
        return f"pr-{match.group(1)}"
    run_id = manifest.get("run.id")
    if run_id:
        return run_id
    return Path(fallback).stem


def run(cmd: list[str], cwd: Path, check: bool = True) -> int:
    print("+", " ".join(cmd))
    proc = subprocess.run(cmd, cwd=cwd, check=check)
    return proc.returncode


def main() -> int:
    parser = argparse.ArgumentParser(description="Run local SEO and quality review from a manifest.")
    parser.add_argument("--manifest", required=True, help="Path to translation-flow manifest YAML.")
    parser.add_argument("--target-root", required=True, help="Path to the translated blog repository.")
    parser.add_argument("--reports-root", default="reports", help="Directory where reports are written.")
    args = parser.parse_args()

    repo_root = Path(__file__).resolve().parents[1]
    manifest_path = Path(args.manifest).resolve()
    target_root = Path(args.target_root).resolve()
    reports_root = (repo_root / args.reports_root).resolve()
    manifest = read_simple_manifest(manifest_path)
    report_id = report_id_for_manifest(manifest, manifest_path.name)
    report_dir = reports_root / report_id
    report_dir.mkdir(parents=True, exist_ok=True)

    manifest_copy = report_dir / "manifest.yaml"
    shutil.copyfile(manifest_path, manifest_copy)

    request = "\n".join(
        [
            "# Review Request",
            "",
            f"- Target repo: {manifest.get('translation.target_repo', '')}",
            f"- Branch: {manifest.get('translation.branch', '')}",
            f"- File path: {manifest.get('translation.file_path', '')}",
            f"- PR URL: {manifest.get('translation.pr_url', '')}",
            "",
            "SEO and quality reports were generated by the local hf workflow runner.",
            "",
        ]
    )
    (report_dir / "request.md").write_text(request)

    # The SEO eval gate exits non-zero when the post fails; we still want the
    # report written, so don't raise — surface the gate result instead.
    seo_code = run(
        [
            "python3",
            "skills/seo/tools/seo_eval.py",
            "--manifest",
            str(manifest_copy),
            "--target-root",
            str(target_root),
            "--output",
            str(report_dir / "seo-report.md"),
            "--json",
            str(report_dir / "seo-eval.json"),
        ],
        cwd=repo_root,
        check=False,
    )
    print(f"SEO gate: {'PASS' if seo_code == 0 else 'FAIL'} (exit {seo_code})")
    run(
        [
            "python3",
            "skills/seo/tools/metadata_suggestion.py",
            "--file",
            manifest.get("translation.file_path", ""),
            "--target-root",
            str(target_root),
            "--eval-json",
            str(report_dir / "seo-eval.json"),
            "--output",
            str(report_dir / "metadata-suggestion.json"),
            "--manifest",
            str(manifest_copy),
            "--report-path",
            str(report_dir / "seo-report.md"),
        ],
        cwd=repo_root,
    )
    run(
        [
            "python3",
            "skills/quality/tools/simple_quality_report.py",
            "--manifest",
            str(manifest_copy),
            "--target-root",
            str(target_root),
            "--output",
            str(report_dir / "quality-report.md"),
        ],
        cwd=repo_root,
    )

    print(f"Wrote reports to {report_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
